api/urls.py
from django.conf.urls.defaults import *
from piston.resource import Resource
from devmgr.api.handlers import *

# TODO: CSRF protection currently disabled...fix this!
# The below is stolen from Taedium, maybe I can use that
"""
class CSRFDisabledResource(Resource):
    def __init__(self, **kwargs):
	super(self.__class>>, self).__init__(**kwargs)
	self.csrf_exempt = getattr(self.handler, 'csrf_exmpt', True)

#Uses Django authentication by default
auth = HttpBasicAuthentication()
"""
#device_handler = CSRFDisabledResource(handler=DeviceHandler, authentication=auth)

device_handler = Resource(DeviceHandler)
device_location_handler = Resource(DeviceLocationHandler)
device_allow_track_handler = Resource(DeviceAllowTrackHandler)
device_wipe_handler= Resource(DeviceWipeHandler)
device_c2dm_register_handler = Resource(DeviceC2DMRegisterHandler)
device_c2dm_send_handler = Resource(C2DMSendHandler)
device_loc_frequency_handler = Resource(LocFrequencyHandler)

urlpatterns = patterns('',
    (r'^register$', device_handler),
    (r'^(?P<device_id>\d+)$', device_handler),
    (r'^$', device_handler),
    (r'^(?P<device_id>\d+)/location$', device_location_handler),
    (r'^(?P<device_id>\d+)/allowtrack$', device_allow_track_handler),
    (r'^(?P<device_id>\d+)/wipestatus$', device_wipe_handler),
    (r'^c2dm/(?P<device_id>\d+)/register$', device_c2dm_register_handler),
    (r'^c2dm/(?P<device_id>\d+)/send$', device_c2dm_send_handler),
    (r'^(?P<device_id>\d+)/trackfrequency$', device_loc_frequency_handler),
)

devices/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('devices.views',
    (r'^$', 'index'),
    (r'^(?P<device_id>\d+)/wipe/$', 'wipe'),
    (r'^(?P<device_id>\d+)/trackfrequency', 'update_track_frequency'),
    (r'^(?P<device_id>\d+)/send/$', 'send_c2dm'),
)

urls.py
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^devices/', include('devices.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^api/', include('devmgr.api.urls')),
)

devices/models.py
from django.db import models
from datetime import datetime

class Device(models.Model):
    name = models.CharField(max_length=150)
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    allow_tracking = models.BooleanField()
    track_frequency = models.IntegerField()
    is_wiped = models.BooleanField()
    wipe_requested = models.BooleanField()
    google_id = models.CharField(max_length=255)
    loc_timestamp = models.BigIntegerField()

    def __unicode__(self):
	return self.name

    def to_dict(self):
	dict = {
	    'id': self.id,
	    'name': self.name,
	    'latitude': self.latitude,
	    'longitude': self.longitude,
	    'allow_tracking': self.allow_tracking,
	    'track_frequency': self.track_frequency,
	    'is_wiped': self.is_wiped,
	    'wipe_requested': self.wipe_requested,
	    'google_id': self.google_id,
	    'loc_timestamp': self.loc_timestamp
	}
	return dict

    def getFormattedTimestamp(self):
	return datetime.utcfromtimestamp(self.loc_timestamp/1000)

devices/forms.py
from django import forms

class LocationForm(forms.Form):
    track_frequency = forms.CharField(max_length=12)

devices/views.py
from django.shortcuts import render_to_response, get_object_or_404
from devices.models import Device
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
#from devmgr.c2dm.c2dm_sender import C2DMSender
from django import forms
from devices.forms import *

# Main page
def index(request):
    # Show first 5 devices
    device_list = Device.objects.all().order_by('-id')[:5]
    location_form = LocationForm()
    return render_to_response('devices/index.html', {'device_list': device_list, 'location_form': location_form},
				context_instance=RequestContext(request))

# Mark a device to be wiped
def wipe(request, device_id):

    device = get_object_or_404(Device, pk=device_id)
    device.wipe_requested = True
    device.save()

    return HttpResponseRedirect(reverse('devices.views.index'))

# Change the frequency with which a device reports it's location
def update_track_frequency(request, device_id):

    device = get_object_or_404(Device, pk=device_id)

    if request.method == 'POST':
	form = LocationForm(request.POST)
	if form.is_valid():
	    track_frequency = form.cleaned_data['track_frequency']
	    device.track_frequency = track_frequency
	    device.save()

	    # Send a c2dm message to device notifying of change in update frequency
	    # success = C2DMSender().send_push_msg(device_id, 'track_frequency')

    return HttpResponseRedirect(reverse('devices.views.index'))

# Test: Send a random C2DM message to the app
def send_c2dm(request, device_id):
    print "Sending push notification to device %s" % device_id
    success = C2DMSender().send_push_msg(device_id, "sent msg from the website")
    print success
    return HttpResponseRedirect(reverse('devices.views.index'))

templates/devices/index.html
<h1>Device List</h1>
{% if device_list %}
    <ul>
    {% for device in device_list %}
	<li>
	    <h3>{{ device.name }}</h3>
	    <b>Location Information</b>
	    {% if device.allow_tracking %}
		<br>Latitude: {{ device.latitude }}
		<br>Longitude: {{ device.longitude }}
		<br>Timestamp: {{ device.getFormattedTimestamp }}
		<form action="/devices/{{ device.id }}/trackfrequency" method="post">
		{% csrf_token %}
		{{ form.non_field_errors }}
		<div class="fieldWrapper">
		    {{ location_form.track_frequency.errors }}
		    Current frequency of location checks: {{ device.track_frequency }} seconds
		    <br><label for="id_track_frequency">New frequency of location checks:</label>
		    {{ location_form.track_frequency }}
		</div>
		<input type="submit" value="Update frequency" />
		</form>
	    {% else %}
		Tracking is not enabled for this device.
	    {% endif %}

	    <br><b>Wipe Information</b>
	    {% if device.wipe_requested %}
		<br>Wipe initiated
		{% if device.is_wiped %}
		    <br>Status: Completed
		{% else %}
		    <br>Status: Pending
		{% endif %}
	    {% else %}
		<br>Wipe not requested
	    {% endif %}
	    <!--
	    <br><b>Push Enabled</b>
	    {% if device.google_id != "" %}
		<br>Yes: {{ device.google_id }}
	    {% else %}
		<br>No
	    {% endif %}
	    <form action= "/devices/{{ device.id }}/send/" method="post">
	    {% csrf_token %}
	    <input type="submit" value="Send Push Notification" />
	    </form>
	    -->
	    <br>
	    <form action="/devices/{{ device.id }}/wipe/" method="post">
	    {% csrf_token %}
	    <input type="submit" value="Wipe device" /> 
	    </form>
	</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No devices are registered.</p>
{% endif %}